import React, {Suspense,lazy,useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowDown,ArrowRight,ArrowUp,Sun,Moon,Menu,X,Github,Copy,Check,Code2,Terminal,Layers,Zap,Accessibility,MapPin,Download,Plus,Minus,ExternalLink,Linkedin} from 'lucide-react';
import {profile,projects,experience,skills} from './data';
import './style.css';
import Hero from './Hero.jsx';
// Below-the-fold sections load as separate chunks, fetched in the background once the page is idle.
const loadStories=()=>import('./Stories.jsx'),loadToolkit=()=>import('./Toolkit.jsx');
const Stories=lazy(loadStories),Toolkit=lazy(loadToolkit);
const idle=cb=>window.requestIdleCallback?requestIdleCallback(cb,{timeout:2000}):setTimeout(cb,1200);
if(typeof window!=='undefined')idle(()=>{loadToolkit();loadStories()});
import Journey from './Journey.jsx';
const nav=[['about','About'],['projects','Work'],['experience','Experience'],['toolkit','Toolkit'],['stories','Stories']];
function useTheme(){const [dark,setDark]=useState(()=>{try{return localStorage.getItem('theme')==='dark'}catch{return false}});useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';try{localStorage.setItem('theme',dark?'dark':'light')}catch{}},[dark]);return [dark,setDark]}
function App(){
 const [dark,setDark]=useTheme(),[menu,setMenu]=useState(false),[filter,setFilter]=useState('All'),[expanded,setExpanded]=useState(false),[selected,setSelected]=useState(null),[copied,setCopied]=useState(false),[time,setTime]=useState(''),[active,setActive]=useState('home');
 const dialog=useRef(null),lastFocus=useRef(null);
 useEffect(()=>{const update=()=>setTime(new Intl.DateTimeFormat('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'}).format(new Date()));update();const i=setInterval(update,60000);return()=>clearInterval(i)},[]);
 useEffect(()=>{const ob=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting)setActive(e.target.id)})},{rootMargin:'-15% 0px -60% 0px'});const watch=()=>{ob.disconnect();document.querySelectorAll('main > section[id]').forEach(el=>ob.observe(el))};watch();const mo=new MutationObserver(watch);mo.observe(document.querySelector('main'),{childList:true});return()=>{ob.disconnect();mo.disconnect()}},[]);
 useEffect(()=>{if(selected){lastFocus.current=document.activeElement;dialog.current.showModal();document.body.style.overflow='hidden'}else{dialog.current?.close();document.body.style.overflow='';lastFocus.current?.focus()}return()=>{document.body.style.overflow=''}},[selected]);
 async function copy(){try{await navigator.clipboard.writeText(profile.email);setCopied(true);setTimeout(()=>setCopied(false),2200)}catch{window.location.href=`mailto:${profile.email}`}}
 const filtered=projects.filter(p=>filter==='All'||p.category===filter);
 return <><a className="skip" href="#about">Skip to content</a><div className="floating-dock"><a className="dock-home" href="#home" aria-label="Aafthab home">a.</a><nav aria-label="Main navigation">{nav.map(([id,label])=><a className={active===id?'active':''} key={id} href={'#'+id}>{label}</a>)}</nav><a className="dock-talk" href="#contact">Let’s talk <ArrowUpRight size={17}/></a><button className="icon-button mobile-toggle" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>
 {menu&&<nav className="mobile-nav" aria-label="Mobile navigation">{[...nav,['contact','Contact']].map(([id,label])=><a key={id} href={'#'+id} onClick={()=>setMenu(false)}>{label}<ArrowUpRight/></a>)}</nav>}
 <main><Hero dark={dark} setDark={setDark} time={time}/>
 <section id="about" className="about section"><SectionLabel number="01" title="A little about me"/><div className="about-layout"><div><p className="intro">Hey, I’m Aafthab <span className="wave">👋</span></p><h2>A curious mind.<br/>A builder at heart.</h2><p className="body-copy">{profile.summary}</p><p className="body-copy">Currently studying at <strong>GITAM University</strong> and looking for my next opportunity to build meaningful software.</p><a href={profile.resumeUrl} target="_blank" rel="noreferrer" className="text-link" download>Download résumé (PDF) <Download size={16}/></a></div><TerminalCard/></div></section>
 <section id="projects" className="section projects"><div className="section-heading"><div><SectionLabel number="02" title="Selected work"/><h2>Built with purpose<span className="accent">.</span></h2></div><span className="mono secondary">IDEAS → WORKING SOFTWARE</span></div><div className="filter-row"><div className="filters" aria-label="Filter projects">{['All','Full stack','AI / ML'].map(f=><button key={f} aria-pressed={filter===f} className={filter===f?'selected':''} onClick={()=>{setFilter(f);setExpanded(false)}}>{f}{f==='All'&&<span>04</span>}</button>)}</div><span className="mono secondary">{String(filtered.length).padStart(2,'0')} PROJECTS</span></div><div className="project-grid">{filtered.slice(0,expanded?99:3).map((p,i)=><button key={p.id} className="project-card" onClick={()=>setSelected(p)} aria-label={`View ${p.name} project`}><div className={'project-visual '+p.color}><ProjectPreview project={p}/><span className="preview-label">INTERFACE CONCEPT</span><span className="project-open"><ArrowUpRight size={22}/></span></div><div className="project-info"><div className="mono project-category">{p.eyebrow}<span>{p.date}</span></div><h3>{p.name}</h3><p>{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div></button>)}</div>{filtered.length>3&&<button className="outline-button load" onClick={()=>setExpanded(!expanded)}>{expanded?'Show less':'View all projects'} {expanded?<Minus size={16}/>:<Plus size={16}/>}</button>}</section>
 <section className="principles section"><SectionLabel number="03" title="How I build"/><div className="principles-layout"><h2>Good software.<br/>No shortcuts.</h2><div className="principle-grid">{[[Layers,'Built to scale','Thoughtful architecture, dependable APIs, and clean separation of concerns.'],[Accessibility,'Made for people','Responsive, accessible interfaces that feel natural on every screen.'],[Zap,'Fast by intention','Performance considered from the first decision, not the final sprint.'],[Code2,'Tested, then shipped','Automated checks and repeatable builds for confidence in every release.']].map(([Icon,title,desc])=><div className="principle" key={title}><Icon size={23}/><h3>{title}</h3><p>{desc}</p></div>)}</div></div></section>
 <section id="experience" className="section"><div className="section-heading"><div><SectionLabel number="04" title="The journey so far"/><h2>Learning by doing<span className="accent">.</span></h2></div><span className="mono secondary">2025 — 2026</span></div><Journey/><div className="education"><div><span className="mono secondary">EDUCATION</span><h3>GITAM University</h3><p>B.Tech in Computer Science · 2023 — Present</p><span className="small-label">CGPA 8.06</span></div><div><span className="mono secondary">BEYOND THE CLASSROOM</span><h3>Always expanding the toolkit.</h3><p>Microsoft Azure AI Fundamentals (AI-900) · Score 781</p><p>Core Member · Google Developers Group, GITAM</p></div></div></section>
 <Suspense fallback={<section id="toolkit" className="section-placeholder"/>}><Toolkit extra={'Also in the toolkit: '+[...skills['Foundations'],'REST APIs','Static analysis','GitLab Runner'].join(' · ')+'.'}/></Suspense>
 <Suspense fallback={<section id="stories" className="section-placeholder"/>}><Stories/></Suspense>
 <section id="contact" className="contact section"><div className="contact-top"><SectionLabel number="07" title="Have something in mind?"/><span className="available"><i/> Let’s build something good</span></div><a className="contact-title" href={`mailto:${profile.email}`}>LET’S TALK<span><ArrowUpRight/></span></a><div className="contact-bottom"><div className="email-row"><a href={`mailto:${profile.email}`}>{profile.email}</a><button className="icon-button" aria-label="Copy email address" onClick={copy}>{copied?<Check size={19}/>:<Copy size={19}/>}</button><span className="copy-status" role="status">{copied?'Copied!':''}</span></div>{profile.linkedin&&<a className="contact-linkedin" href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={18}/> LinkedIn <ArrowUpRight size={16}/></a>}</div></section>
 </main><footer><a className="brand" href="#home">a<span>.</span></a><p>Designed with intention. Built by Aafthab.</p><div className="footer-socials">{profile.github&&<a href={profile.github} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={13}/></a>}{profile.linkedin&&<a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={13}/></a>}<span>© {new Date().getFullYear()}</span><a href="#home" aria-label="Back to top" className="icon-button"><ArrowUp size={18}/></a></div></footer>
 <dialog ref={dialog} aria-labelledby="project-title" className="project-dialog" onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===dialog.current)setSelected(null)}}>{selected&&<><button className="dialog-close icon-button" aria-label="Close project" onClick={()=>setSelected(null)}><X/></button><div className={'dialog-art project-visual '+selected.color}><ProjectPreview project={selected}/><span className="preview-label">INTERFACE CONCEPT</span></div><div className="dialog-content"><span className="mono secondary">{selected.category} · {selected.date}</span><h2 id="project-title">{selected.name}</h2><p>{selected.summary}</p><h3>What went into it</h3><ul>{selected.features.map(f=><li key={f}>{f}</li>)}</ul><div className="tags">{selected.tags.map(t=><span key={t}>{t}</span>)}</div><div className="dialog-links">{selected.live&&<a className="solid-button" href={selected.live} target="_blank" rel="noreferrer">Live project <ExternalLink size={16}/></a>}{selected.github&&<a className="outline-button" href={selected.github} target="_blank" rel="noreferrer">Source code <Github size={16}/></a>}<a className="text-link" href={`mailto:${profile.email}?subject=${encodeURIComponent('Tell me more about '+selected.name)}`}>Ask me about this project <ArrowUpRight size={16}/></a></div></div></>}</dialog></>;
}
function SectionLabel({number,title}){return <div className="section-label mono"><span>{number} /</span> {title.toUpperCase()}</div>}
function TerminalCard(){const [input,setInput]=useState(''),[history,setHistory]=useState([{command:'whoami',output:'Aafthab Ali Shaik\nSoftware engineer. Lifelong learner.'},{command:'cat interests.txt',output:'full-stack development · machine learning\nclean architecture · things that just work'}]);const scroll=useRef(null);function run(e){e.preventDefault();const command=input.trim();if(!command)return;const c=command.toLowerCase();if(c==='clear')setHistory([]);else {const output={help:'Try: whoami, skills, projects, education, contact, clear',whoami:`${profile.name}\n${profile.role} · ${profile.location}`,skills:'React · TypeScript · Node.js · Python\nFastAPI · Docker · PostgreSQL',projects:projects.map(p=>p.name).join('\n'),education:'B.Tech Computer Science · GITAM University\n2023 — Present · CGPA 8.06',contact:profile.email}[c]||`Command not found: ${command}\nType help to see available commands.`;setHistory(h=>[...h.slice(-15),{command,output}])}setInput('')}
 useEffect(()=>{if(scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight},[history]);return <div className="terminal"><div className="terminal-bar"><div><i/><i/><i/></div><span>aafthab — portfolio</span><Terminal size={13}/></div><div className="terminal-body" ref={scroll}><p className="terminal-hint">A small window into my world.</p><div aria-live="polite" aria-relevant="additions">{history.map((h,i)=><div className="terminal-entry" key={i}><p><span>➜</span> <b>~</b> {h.command}</p><pre>{h.output}</pre></div>)}</div><form onSubmit={run}><label htmlFor="terminal-input"><span>➜</span> <b>~</b><span className="sr-only">Terminal command</span></label><input autoComplete="off" spellCheck="false" id="terminal-input" value={input} onChange={e=>setInput(e.target.value)} placeholder="type help"/><button aria-label="Run command" type="submit"><ArrowRight size={15}/></button></form></div><div className="terminal-footer"><i/> ALL SYSTEMS CURIOUS <span>UTF-8</span></div></div>}
function ProjectPreview({project}){if(project.id==='routewise')return <div className="mini-app route-app" aria-hidden="true"><div className="mini-header"><b>↗ routewise</b><span>VISAKHAPATNAM</span></div><div className="route-content"><h4>Your city.<br/>Your way.</h4><div className="route-stops"><span>● &nbsp; GITAM University</span><span>◎ &nbsp; RK Beach</span></div><div className="route-result"><span>BUS + WALK <b>38 min</b></span><strong>₹ 25 <small>estimated</small></strong></div><div className="mini-action">Find my route <ArrowRight size={12}/></div></div></div>;if(project.id==='expression')return <div className="mini-app expression-app" aria-hidden="true"><div className="mini-header"><b>expression<span>®</span></b><span>LIVE ANALYSIS</span></div><div className="face-scan"><span className="scan-corner tl"/><span className="scan-corner tr"/><span className="scan-corner bl"/><span className="scan-corner br"/><span className="face-symbol">☺</span><span className="scan-tag">HAPPY</span></div><div className="emotion"><span>Happiness</span><span>Illustrative preview</span></div><div className="emotion-bar"><i/></div></div>;if(project.id==='taxpal')return <div className="mini-app tax-app" aria-hidden="true"><div className="mini-header"><b>taxpal<span>✳</span></b><span>OVERVIEW</span></div><div className="tax-content"><span className="mini-muted">Your financial overview</span><h4>More clarity.<br/>Less guesswork.</h4><div className="chart">{[35,57,43,72,59,90,76,98].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div><div className="chart-legend"><span>INCOME</span><span>EXPENSES</span><span>SAVINGS</span></div></div></div>;return <div className="mini-app voice-app" aria-hidden="true"><div className="mini-header"><b>voice / ai</b><span>LISTENING</span></div><h4>What’s on<br/>your mind?</h4><div className="waveform">{[20,35,55,32,68,83,45,70,95,65,40,60,30,45,20].map((h,i)=><i key={i} style={{height:h+'%'}}/>)}</div><span className="mini-muted">A conversation away.</span></div>}

createRoot(document.getElementById('root')).render(<App/>);
